spring:
    application:
        name: server
    config:
        import: "optional:configserver:"
    rabbitmq:
        host: 127.0.0.1
        port: 5673
        username: user
        password: password
    cloud:
        bus:
            enabled: true
            refresh:
                enabled: true
#        config:
#            fail-fast: true

management:
    endpoints:
        web:
            exposure:
                include: "*"
    security:
        enabled: false
