[versions]
spring-boot = "3.3.2"
lombok = "1.18.34"

[libraries]
spring-boot-plugin = { module = "org.springframework.boot:spring-boot-gradle-plugin", version.ref = "spring-boot"}
lombok = { module = "org.projectlombok:lombok", version.ref = "lombok"}
