server:
    port: 8888

spring:
    application:
        name: server
    cloud:
        config:
            server:
                git:
                    uri: https://github.com/willisSantos/git-lfs-test-github
                    skipSslValidation: true
                    defaultLabel: master
